create table sofla (
lname VARCHAR (18), 
rname VARCHAR (20), 
CITY VARCHAR (18), 
STATE VARCHAR (2), 
ZIP VARCHAR (5), 
OCCUPATION VARCHAR (35), 
CONT_DATE DATE, 
AMOUNT FLOAT, 
PRIMGEN CHAR (1), 
CAND_ID VARCHAR (9)
)
